### ISSUE TITLE
Test string util classes

### ISSUE THREAD

**Issue by gabrielbarker** [forcedotcom/lightning-language-server#247]
Hey team, 

I noticed that the coverage for this project is quite low, so I've written a few tests to boost it a little bit. Hopefully this helps a little, but if it complicates things then feel free to close this issue and my PR.

I have written tests for `string-util.ts` in the aura server and `strings.ts` in lightning lsp common.

Thanks!

**Comment by lcampos** [comment]
Closing this since the changes were merged. Thanks again for the contribution @gabrielbarker
