### ISSUE TITLE
jsconfig missing custom component mappings

### ISSUE THREAD

**Issue by csuich2** [forcedotcom/lightning-language-server#284]
### Summary

Prior to #160 being merged, it appears that the language server updated `jsconfig.json` with the path mappings for all of the custom components. The jsconfig is now missing those path mappings.

https://github.com/forcedotcom/lightning-language-server/pull/160/files?file-filters%5B%5D=.ts#diff-4b7a3b1ab597038eec23858a6d9416228da45d15adfe986c56312708938403a1L32

The most apparent implication is that ctrl-click to open no longer works in editors like VSCode.

### Steps To Reproduce:

1.  Create a new project
1.  Add some custom components
1. Import one component from another
1. Note that ctrl-click no longer works
1. Note that `jsconfig.json` does not have the path mappings for the new components.

### Expected result

`jsconfig.json` should have the correct path mappings to allow the editor and tools like TypeScript to be aware of the mappings.

### Actual result

The mappings are not present.

### Additional information

N/A

**VS Code Version**: 1.50.1

**SFDX CLI Version**: sfdx-cli/7.78.1-5a65d9dd2f darwin-x64 node-v12.18.3

**OS and version**: MacOS 10.15.7

**Comment by csuich2** [comment]
@mrmicahcooper Sorry to tag, but just wanted to see if you have insight into why this functionality was removed with #160 and if you knew anything about the Apex and sobject typings missing as well in #285

Thanks!

**Comment by lcampos** [comment]
@csuich2 the data that used to be added to `jsconfig.json` was used by the language server when it was indexing all the components in a project. In the past months we did a big refactor that changed the way we index a project and we simplified the output to `jsconfig.json`. This is what is used for features like autocompletions, code navigation, etc. 

I'll close this for now but feel free to re-open if there is a regression.
