### ISSUE TITLE
Generated Apex and sobject typings missing

### ISSUE THREAD

**Issue by csuich2** [forcedotcom/lightning-language-server#285]
### Summary

With a previous version of the language server typings for Apex code and sobjects were generated and placed into the .sfdx. folder. Those files are now missing. We were attempting to write our managed package with TypeScript, but those typings missing is a huge blow to our effort.

I was able to trace the missing `jsconfig.json` path mappings for #284 to a specific PR, but haven't yet been able to trace why these files are missing.

Can we restore this functionality?

### Steps To Reproduce:

1.  Create a new project
1.  Add Apex code or custom objects
1.  Note that there are no longer typings for the Apex code or sobjects

### Expected result

TS typings should be generated for Apex code as well as sobjects.

### Actual result

TS typings are not present.

### Additional information

See this screenshot from my `.sfdx` folder which was generated by a previous version of the sfdx CLI. I upgraded the CLI a while back and just now noticed that these files are no longer generated.
![image](https://user-images.githubusercontent.com/1966632/98136528-07814100-1e8f-11eb-8347-f21652bd6405.png)

**VS Code Version**: 1.50.1

**SFDX CLI Version**: sfdx-cli/7.78.1-5a65d9dd2f darwin-x64 node-v12.18.3

**OS and version**: MacOS 10.15.7

**Comment by sshumake** [comment]
@nrkruk @midzelis - Hey Friends! @csuich2 ran into this issue in addition to #284 were they both worked a few months ago but no longer work on the latest version.  Any chance either of you can take a look and see if this can be added back? :)

**Comment by lcampos** [comment]
Hi @csuich2 , the typings for Apex and SObjects are generated by the Apex language server and are still getting stored under `.sfdx/typings/lwc/apex` and `.sfdx/typings/lwc/sobjects`.
You'll need to configure the Apex extension for VSCode which is part of the [Salesforce Extension Pack](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode) for this to work on your project.
