### ISSUE TITLE
  Message: Request textDocument/definition failed with message: Cannot destructure property 'delimiter' of '(intermediate value)(intermediate value)(intermediate value)' as it is undefined.

### ISSUE THREAD

**Issue by santoshraman** [forcedotcom/lightning-language-server#297]
LWC Langauge Server:
[Error - 2:15:54 PM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot destructure property 'delimiter' of '(intermediate value)(intermediate value)(intermediate value)' as it is undefined.
  Code: -32603 

Getting this error when hovering over Aura component js files.

sfdx version:
sfdx-cli/7.81.0-7b953c80d1 darwin-x64 node-v12.18.3

**Comment by lcampos** [comment]
Thanks for opening this issue @santoshraman . The fix was merged in PR https://github.com/forcedotcom/lightning-language-server/pull/292
