### ISSUE TITLE
@api get recordId and @api set recordId detected in class declaration. Only one of the two needs to be decorated with @api.

### ISSUE THREAD

**Issue by ytiq** [forcedotcom/lightning-language-server#464]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

No Error from ESLint is shown

### Actual result

@api get recordId and @api set recordId detected in class declaration. Only one of the two needs to be decorated with @api.

### Additional information

Here is an example of LWC component and error producing code snippet down below
https://webcomponents.dev/edit/4TuiynUFc1ccniIlgo2L

```js
import { LightningElement, api } from 'lwc';

export default class Testsdfsdf extends LightningElement {
    @api get b() {}
    @api set a(value) { }
    get a() {}
}
```

If at any place in the project you have `@api get` in the component then adding `@api set` will give you an error

**VS Code Version**: 1.62

**SFDX CLI Version**:  sfdx-cli/7.127.0 darwin-x64 node-v16.13.0

**OS and version**: macOs Catalina 10.15.7

**Comment by AllanOricil** [comment]
@pmdartus @nolanlawson I confirm @ytiq isolated the problem correctly. It is not an issue related to vscode not loading the language server.



steps:

1 - create a lwc with the following code
````js
import { LightningElement, api } from 'lwc';

export default class Test extends LightningElement {

    _test;
    @api set test(value){}
}
````
2 - verify it does work and no language server error is present
3 - change the lwc code to this one
````js
import { LightningElement, api } from 'lwc';

export default class Test extends LightningElement {

    _test;
    @api set test(value){}
    @api get bla(){}
}
````
4 - verify that now you have the error from this issue

**Comment by AllanOricil** [comment]
https://github.com/salesforce/lwc/issues/2406
https://github.com/salesforce/eslint-config-lwc/issues/66

**Comment by ytiq** [comment]
@AllanOricil weirdly enough, I tried adding my code as a test and it passes, so it might not be directly related to the latest version of lightning-language-server. I tried looking into dependencies of VS Code plugins itself and it seems that the latest `lwc-language-server` is using `"@lwc/compiler": "0.34.8"` which is 3 years old, so might be related to it

**Comment by randi274** [comment]
Thanks for logging this! Since we're tracking it over in the extensions repo with [#3704](https://github.com/forcedotcom/salesforcedx-vscode/issues/3704), I'll close this issue in favor of that one for now.
