### ISSUE TITLE
Viewing LWC code produces errors in `LWC Language Server` tab

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/lightning-language-server#493]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1. Open a LWC js file (sometimes takes a couple of files)
2. Switch to LWC Language Server output tab

### Expected result

There are no errors if your component is composed correctly

### Actual result

```
[Error - 11:16:49 AM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'find' of undefined
  Code: -32603 
```

### Additional information

**Salesforce Extension Version in VS Code**: v52.13.0

**SFDX CLI Version**: sfdx-cli/7.116.2 darwin-x64 node-v14.17.5

**OS and version**: macOS Big Sur 11.6

**Comment by klewis-sfdc** [comment]
Closed per merge of https://github.com/forcedotcom/salesforcedx-vscode/pull/4216
