### ISSUE TITLE
LWC Language Server errors on load when config.blt is not present

### ISSUE THREAD

**Issue by trevor-bliss** [forcedotcom/lightning-language-server#497]
### Summary

Salesforce VS Code Extensions fail to load due to the following error when a `config.blt` file is not present on the local machine. I just set up a new laptop with `corecli` and it looks like `config.blt` is no longer a required file for a core workspace.

We should accommodate this scenario by parsing an alternative config file when `config.blt` is not present.

```
[Error: ENOENT: no such file or directory, open '/Users/<user>/blt/config.blt'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/<user>/blt/config.blt'
}
[Error - 3:57:12 PM] Connection to server got closed. Server will not be restarted.
```

I also see the following error popup in VS Code on load:

```
 The LWC Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.
```

### Steps To Reproduce:

1.  Set up core following the latest internal doc (do not use any BLT commands that would init a config.blt file).
2. Install the VS Code Extension Pack from the public marketplace.
3. Restart VS Code.

### Expected result

VS Code loads without error.

### Actual result

The errors above are present.

### Additional information

I see the parsing of `config.blt` done here with no error handling or fallback. We should find an alternative file to read if this line fails:

https://github.com/forcedotcom/lightning-language-server/blob/7cd0d5736b546fb4cab2963a5fb93ea284b8a0b6/packages/lightning-lsp-common/src/context.ts#L485

**VS Code Version**: 1.67.0 (Universal)

**SFDX CLI Version**: 

**OS and version**: macOS Monterey 12.3.1

**Comment by NagarjunaParala** [comment]
Any updates on this issue to resolve?
