### ISSUE TITLE
An error comes up when you try to use the new template directives

### ISSUE THREAD

**Issue by albarivas** [forcedotcom/lightning-language-server#543]
### Summary

An error comes up when you try to use the new template directives
<img width="1086" alt="Screenshot 2023-02-21 at 12 57 48" src="https://user-images.githubusercontent.com/12017842/220343186-5948404c-9685-4ff5-b519-c58a52cbf377.png">

### Steps To Reproduce:

1. Install last version of VS Code extensions
1. Update dev dependencies to last versions
```
"devDependencies": {
    "@lwc/eslint-plugin-lwc": "^1.6.2",
    "@prettier/plugin-xml": "^2.2.0",
    "@sa11y/jest": "^4.1.1",
    "@salesforce/eslint-config-lwc": "^3.4.0",
    "@salesforce/eslint-plugin-lightning": "^1.0.0",
    "@salesforce/sfdx-lwc-jest": "^1.3.0",
    "eslint": "^8.34.0",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-jest": "^27.2.1",
    "husky": "^8.0.3",
    "lint-staged": "^13.1.2",
    "prettier": "^2.8.4",
    "prettier-plugin-apex": "^1.12.0"
  },
```
1.  Write a component on a Salesforce project that uses  <template lwc:if={whatever}></template>

### Expected result

No warning 

### Actual result

<img width="1086" alt="Screenshot 2023-02-21 at 12 57 48" src="https://user-images.githubusercontent.com/12017842/220343423-72c024e6-7dd0-4dde-9056-367c3ba4e1b9.png">

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by randi274** [comment]
Hey @albarivas - I double checked this today on the ebikes-lwc project with v57.2.1 of the extensions, and changed the dependencies, and wasn't able to reproduce the error. We upgraded the lwc libraries a few months ago with #518 and #515. Today in my project I'm seeing that the template directives are looking good, and I'm even seeing contextual errors about the new directives (screenshot below). Feel free to DM me if this is becoming a TDX blocker for you, or if you have any other projects I should try with.

![Screenshot 2023-02-22 at 4 01 30 PM](https://user-images.githubusercontent.com/9795193/220760223-9389d9cd-1dc0-4f76-b3d4-fcc402f4da90.png)

**Comment by albarivas** [comment]
Thanks for taking a look. It happened that although I was updating the salesforce extension pack, the individual extensions were not being updated. Now I can see it working properly. Sorry and thanks!!
